### ISSUE TITLE
Suboptimal Respec

### ISSUE THREAD

**Issue by TheKleopiNetwork** [Zorn192/AutoTrimps#105]
Autotrimps does not assign all Helium on the supported perks.
Usually theres about 1% of the total helium unassigned, even if it could be dumped into the perk specified as dumping perk.

Cant it just randomly assign the rest into the perks in order of priority using "dump max possible into", maybe even using max packrat->max trump->max bait in the end for leftovers?

**Comment by JamesBanana** [comment]
It leaves Helium unassigned due to how JavaScript handles large numbers. 

The biggest number Javascript can handle without risking messing it up is called MAX_SAFE_INTEGER, which equals 9007199254740991 (2^53 - 1). Any larger numbers cannot be guaranteed to provide the expected results when being compared. Leaving some helium unassigned was the simplest way to account for this, solving the issue of sometimes not assigning helium at all.
